# action.yml
name: 'Run Tests'
description: 'A GitHub Action to run tests using a Docker container'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - poetry
    - run
    - pytest
inputs:
  args:
    description: 'Arguments to pass to the Docker container'
    required: false
    default: 'poetry run pytest'