name: Test
on:
  push:
    branches:
      - main
jobs:
  Test-Job:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: actions/run-tests
